FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
  language-pack-ja-base \
  language-pack-ja \
  ibus-mozc \
  fonts-ipafont-gothic \
  fonts-ipafont-mincho \
  curl \
  git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
RUN alias curl='curl --noproxy localhost,127.0.0.1'
RUN update-locale LANG=ja_JP.UTF-8 LANGUAGE=ja_JP:ja
ENV LC_ALL C.UTF-8

# node >=6
# npm <=4
RUN apt-get update && apt-get install -y \
  build-essential \
  nodejs \
  npm

RUN npm cache clean \
 && npm install n -g
RUN n 6.2.1 \
 && ln -sf /usr/local/bin/node /usr/bin/node
RUN apt-get -y purge nodejs \
 && npm update
 
COPY .ssh /.ssh
COPY git.sh /git.sh
RUN /git.sh

RUN npm install -g create-react-native-app

CMD ["/bin/bash"]
